### ISSUE TITLE
[BUG] Kick Command

### ISSUE THREAD

**Issue by nurkaapii** [TheDesignCraftYT/MattiBot#2]
### Existiert schon ein Issue für diesen Fehler?

- [X] Ich habe die existierenden Issues durchgeschaut und nichts gefunden.

### Beschreibe den Fehler

Sobald man den Command mit dem eingestellten Prefix ausführt und als Argument einen User taggt, wird dieser als Button "Owner" festgelegt und dieser kann nur dann die Bestätigung/Abbruch Buttons betätigen.

### Erwartetes Verhalten

Es sollte der User, der den Command abgesendet hat, Rechte auf die Buttons haben.

### Schritte zum Reproduzieren

1. kick @user
2. auf einen der Buttons drücken

### Umgebung

```markdown
- OS: Windows
- Browser/App (+Version): App 10.0.19044
- BotVersion: v1.0.0-alpha.6
```

**Comment by TheDesignCraftYT** [comment]
Der Bug wurde behoben
